id: P8C0F2A51
initial_creation_type: ocr
source_metadata:
  volumes:
    fd742e9893004d35859937c4e7e0e00d:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: ནག་པོ་ཆེན་པོའི་འཕྲིན་ལས་གསང་བའི་སྒྲུབ་ཐབས།
      total_pages: 1856
      volume_number: 14
